default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: check-merge-conflict
      stages: [commit]
    - id: debug-statements
      stages: [commit]
    - id: end-of-file-fixer
      stages: [commit]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    - id: flake8
      stages: [commit]
-   repo: https://github.com/pycqa/pylint
    rev: v2.9.3
    hooks:
    - id: pylint
      stages: [commit]
-   repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
    - id: giticket
      args:
       - '--regex=\d{8,}'
       - '--mode=regex_match'
       - '--format=[{ticket}]: {commit_msg}'
